name: create release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install dependencies
        run: yarn install
      - name: Generate changelog
        if: "!startsWith(github.event.head_commit.message, '[VERSION]')"
        id: semantic-release
        run: |
          CHANGELOG=$(yarn run git-conventional-commits changelog | tail -n +3 | head -n -1)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo $CHANGELOG >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          VERSION=$(yarn run git-conventional-commits version | tail -2 | head -1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          yarn version ${{ steps.semantic-release.outputs.VERSION }}
          mkdir -p docs/
          touch docs/CHANGELOG.md
          echo $CHANGELOG | cat - docs/CHANGELOG.md > temp.md && mv temp.md docs/CHANGELOG.md
          rm -rf .git/hooks/commit-msg
          git config --unset core.hooksPath
          git add -A
      - name: Create Pull Request to update master
        if: "!startsWith(github.event.head_commit.message, '[VERSION]')"
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[VERSION] v${{ steps.semantic-release.outputs.VERSION }}"
          title: "[VERSION] v${{ steps.semantic-release.outputs.VERSION }}"
          body: "This PR is autogenerated"
          branch: version/${{ steps.semantic-release.outputs.VERSION }}
          base: master
      - name: Create release
        if: "!startsWith(github.event.head_commit.message, '[VERSION]')"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic-release.outputs.VERSION }}
          release_name: v${{ steps.semantic-release.outputs.VERSION }}
          body: ${{ steps.semantic-release.outputs.CHANGELOG }}
          replaceArtifacts: false
      - name: Create Pull Request to update develop
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "[VERSION] v${{ steps.semantic-release.outputs.VERSION }} - bump `develop`"
          title: "[VERSION] v${{ steps.semantic-release.outputs.VERSION }} - bump `develop`"
          body: "This PR is autogenerated and serves to keep `develop` in sync with `master`"
          branch: version/${{ steps.semantic-release.outputs.VERSION }}
          base: develop
